/**
 * Shell Script Generator - 将菜单 JSON 转换为交互式 bash 脚本
 * 按需下载：点击时静默下载到本地临时文件，再本地执行，确保能看到运行过程
 */

const menuManager = require('../services/menuManager');

/**
 * 生成主脚本
 * @param {string} baseUrl - 服务器基础 URL
 */
function generateMainScript(baseUrl) {
  const data = menuManager.getMenuData();
  const config = data.config || {};
  const items = data.items || [];

  return generateMenuScript(items, config, baseUrl, null);
}

/**
 * 生成子菜单脚本
 * @param {string} submenuId - 子菜单 ID
 * @param {string} baseUrl - 服务器基础 URL
 */
function generateSubmenuScript(submenuId, baseUrl) {
  const data = menuManager.getMenuData();
  const config = data.config || {};
  const items = data.items || [];

  const submenu = menuManager.findSubmenu(items, submenuId);
  if (!submenu || !submenu.children) return null;

  return generateMenuScript(submenu.children, config, baseUrl, submenu.name);
}

/**
 * 生成「下载到本地再执行」的代码块
 * 静默下载，本地 bash 执行，执行后清理
 */
function genDownloadAndRun(url) {
  return `      _tmp="/tmp/wf_$$.sh"
      curl -sL "${url}" -o "$_tmp" 2>/dev/null
      if [ -s "$_tmp" ]; then
        bash "$_tmp"
      else
        echo -e "\\033[0;31m❌ 脚本下载失败，请检查网络\\033[0m"
      fi
      rm -f "$_tmp" 2>/dev/null`;
}

/**
 * 核心：生成菜单 bash 脚本
 */
function generateMenuScript(items, config, baseUrl, parentName) {
  const title = config.title || '无风工具箱';
  const version = config.version || '1.2.1';
  const ascii = config.ascii || '';

  const isRoot = !parentName;
  const displayTitle = isRoot ? `${title} v${version}` : `${title} > ${parentName}`;
  const exitLabel = isRoot ? '退出脚本' : '返回上级';

  // 构建菜单显示
  let menuDisplay = '';
  items.forEach((item, index) => {
    const num = String(index + 1).padStart(2, ' ');
    const arrow = item.type === 'submenu' ? '  →' : '';
    menuDisplay += `  echo "  ${num}.  ${item.name}${arrow}"\n`;
  });

  // 构建选择分支
  let caseBlock = '';
  items.forEach((item, index) => {
    const num = index + 1;
    if (item.type === 'submenu') {
      // 子菜单：也改为下载到本地再执行
      caseBlock += `    ${num})\n`;
      caseBlock += genDownloadAndRun(`${baseUrl}/script/${item.id}`) + '\n';
      caseBlock += `      ;;\n`;
    } else if (item.type === 'script') {
      caseBlock += `    ${num})\n`;

      if (item.url) {
        if (item.url.startsWith('http://') || item.url.startsWith('https://')) {
          // HTTP URL：下载到本地再执行
          caseBlock += genDownloadAndRun(item.url) + '\n';
        } else if (item.url.startsWith('bash <')) {
          // bash <(curl ...) 格式：提取 URL 下载执行
          const urlMatch = item.url.match(/curl\s+(?:-[a-zA-Z]+\s+)*([^\s)]+)/);
          if (urlMatch) {
            caseBlock += genDownloadAndRun(urlMatch[1]) + '\n';
          } else {
            caseBlock += `      ${item.url}\n`;
          }
        } else {
          // 直接命令（docker run / git clone 等）
          caseBlock += `      ${item.url}\n`;
        }
      } else {
        caseBlock += `      echo "未配置脚本"\n`;
      }

      caseBlock += `      ;;\n`;
    }
  });

  // 脚本更新：重新拉取自身
  const updateBlock = isRoot ? `    00)
      clear
      echo -e "\\033[0;36m🔄 正在获取最新版本...\\033[0m"
      exec bash <(curl -sL "${baseUrl}/script")
      ;;` : '';

  const script = `#!/bin/bash
# ${title} - Auto Generated Script
# Generated by ScriptBox

clear

${isRoot ? 'while true; do' : ''}

echo ""
${ascii ? ascii.split('\n').map(line => `echo "${line}"`).join('\n') : ''}
echo "${displayTitle}"
echo "------------------------"
${menuDisplay}echo "------------------------"
${isRoot ? `echo "  00.  脚本更新"
echo "------------------------"` : ''}
echo "   0.  ${exitLabel}"
echo "------------------------"
read -p "请输入你的选择: " choice < /dev/tty

case $choice in
${caseBlock}${updateBlock}
    0)
      ${isRoot ? 'echo "感谢使用 ${title}！"; exit 0' : 'exit 0'}
      ;;
    *)
      echo "无效的选择，请重新输入"
      ${isRoot ? '' : 'exit 1'}
      ;;
  esac

${isRoot ? `
  echo ""
  read -p "按回车键继续..." < /dev/tty
  clear
done` : ''}
`;

  return script;
}

module.exports = {
  generateMainScript,
  generateSubmenuScript
};
